/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// src/main.ts
__export(exports, {
  default: () => main_default
});
var import_obsidian = __toModule(require("obsidian"));
var DEFAULT_SETTINGS = {
  clientId: "4500bc3e9924560abc18944655cfa0d3",
  apiKey: "",
  targetFolder: "IMA\u77E5\u8BC6\u5E93",
  lastSyncTime: "",
  selectedKbs: [],
  selectedNotes: {}
};
var ImaPlugin = class extends import_obsidian.Plugin {
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.addCommand({
        id: "sync-ima-select",
        name: "\u9009\u62E9\u77E5\u8BC6\u5E93\u540C\u6B65",
        callback: () => this.showSyncModal()
      });
      this.addCommand({
        id: "sync-ima-full",
        name: "\u5168\u91CF\u540C\u6B65 IMA \u77E5\u8BC6\u5E93",
        callback: () => this.syncAll(true)
      });
      this.addCommand({
        id: "sync-ima-share",
        name: "\u540C\u6B65\u5206\u4EAB\u94FE\u63A5\u7B14\u8BB0",
        callback: () => this.syncFromShareLink()
      });
      this.addCommand({
        id: "sync-ima-notebook",
        name: "\u540C\u6B65\u7B14\u8BB0\u672C\u7B14\u8BB0",
        callback: () => this.syncNotebookNotes()
      });
      this.addRibbonIcon("sync", "IMA \u540C\u6B65", () => {
        this.showSyncModal();
      });
      this.addSettingTab(new ImaSettingTab(this.app, this));
    });
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
      if (!this.settings.selectedKbs)
        this.settings.selectedKbs = [];
      if (!this.settings.selectedNotes)
        this.settings.selectedNotes = {};
      if (!this.settings.targetFolder)
        this.settings.targetFolder = "IMA\u77E5\u8BC6\u5E93";
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
  showSyncModal() {
    return __async(this, null, function* () {
      if (!this.settings.apiKey) {
        new import_obsidian.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E IMA API Key");
        return;
      }
      new KnowledgeBaseModal(this.app, this).open();
    });
  }
  syncFromShareLink(shareUrl = null) {
    return __async(this, null, function* () {
      new ShareNoteModal(this.app, this, shareUrl).open();
    });
  }
  syncNotebookNotes() {
    return __async(this, null, function* () {
      new NotebookNotesModal(this.app, this).open();
    });
  }
  syncAll(fullSync = true, selectedKbIds = null) {
    return __async(this, null, function* () {
      new import_obsidian.Notice("\u5F00\u59CB\u540C\u6B65\u77E5\u8BC6\u5E93...");
      try {
        const api = new ImaApi(this.settings.clientId, this.settings.apiKey);
        const knowledgeBases = yield api.searchAllKnowledgeBases();
        if (!knowledgeBases || knowledgeBases.length === 0) {
          new import_obsidian.Notice("\u672A\u627E\u5230\u53EF\u7528\u7684\u77E5\u8BC6\u5E93");
          return;
        }
        let targetKbs;
        if (selectedKbIds && selectedKbIds.length > 0) {
          targetKbs = knowledgeBases.filter((kb) => selectedKbIds.includes(kb.kb_id));
        } else if (this.settings.selectedKbs.length > 0) {
          targetKbs = knowledgeBases.filter((kb) => this.settings.selectedKbs.includes(kb.kb_id));
        } else {
          targetKbs = knowledgeBases;
        }
        if (targetKbs.length === 0) {
          new import_obsidian.Notice("\u8BF7\u5148\u9009\u62E9\u8981\u540C\u6B65\u7684\u77E5\u8BC6\u5E93\uFF01");
          return;
        }
        let syncedCount = 0;
        let skippedPermission = 0;
        let skippedFolder = 0;
        let skippedEmpty = 0;
        for (const kb of targetKbs) {
          const items = yield api.getAllKnowledgeList(kb.kb_id);
          if (!items || items.length === 0)
            continue;
          for (const item of items) {
            if (item.media_type === 99) {
              skippedFolder++;
              continue;
            }
            let content = null;
            let failReason = "";
            try {
              if (item.media_type === 11) {
                const docResult = yield api.getDocContentWithError(item.media_id);
                if (docResult.success && docResult.content) {
                  content = docResult.content;
                } else {
                  failReason = `get_doc_content \u5931\u8D25: ${docResult.error}`;
                }
              }
              if (!content) {
                const exportResult = yield api.exportMediaWithError(item.media_id);
                if (exportResult.success && exportResult.content) {
                  content = exportResult.content;
                } else {
                  failReason = failReason || `export_media \u5931\u8D25: ${exportResult.error}`;
                }
              }
              if (content) {
                const title = item.title || "\u672A\u547D\u540D";
                const safeTitle = title.replace(/[/\\:*?"<>|]/g, "_").substring(0, 100);
                const filePath = `${this.settings.targetFolder}/${kb.kb_name}/${safeTitle}.md`;
                const frontMatter = this.generateFrontMatter(kb, item);
                yield this.saveFile(filePath, frontMatter + content);
                syncedCount++;
              } else {
                skippedPermission++;
                console.warn(`[IMA] \u8DF3\u8FC7: ${item.title} - ${failReason}`);
              }
            } catch (e) {
              skippedPermission++;
              console.warn(`[IMA] \u8DF3\u8FC7: ${item.title} - ${e.message}`);
            }
          }
        }
        this.settings.lastSyncTime = new Date().toISOString();
        yield this.saveSettings();
        let msg = `\u540C\u6B65 ${syncedCount} \u4E2A\u6587\u4EF6`;
        if (skippedPermission > 0)
          msg += `\uFF0C\u8DF3\u8FC7 ${skippedPermission} \u4E2A\uFF08\u6743\u9650\u4E0D\u8DB3\uFF09`;
        if (skippedFolder > 0)
          msg += `\uFF0C\u8DF3\u8FC7 ${skippedFolder} \u4E2A\u6587\u4EF6\u5939`;
        new import_obsidian.Notice(msg);
      } catch (e) {
        console.error("[IMA] \u540C\u6B65\u5931\u8D25:", e);
        new import_obsidian.Notice("\u540C\u6B65\u5931\u8D25: " + e.message);
      }
    });
  }
  generateFrontMatter(kb, item) {
    return `---
source: IMA\u77E5\u8BC6\u5E93
kb_name: "${(kb == null ? void 0 : kb.kb_name) || "\u672A\u77E5"}"
title: "${item.title}"
media_id: "${item.media_id}"
media_type: ${item.media_type}
sync_time: "${new Date().toISOString()}"
---

`;
  }
  saveFile(path, content) {
    return __async(this, null, function* () {
      const normalizedPath = path.replace(/[/\\]+/g, "/");
      const folders = normalizedPath.split("/").slice(0, -1);
      let currentPath = "";
      for (const folder of folders) {
        currentPath += folder + "/";
        const folderPath = currentPath.slice(0, -1);
        if (!this.app.vault.getAbstractFileByPath(folderPath)) {
          yield this.app.vault.createFolder(folderPath);
        }
      }
      const existingFile = this.app.vault.getAbstractFileByPath(normalizedPath);
      if (existingFile) {
        yield this.app.vault.modify(existingFile, content);
      } else {
        yield this.app.vault.create(normalizedPath, content);
      }
    });
  }
};
var ImaApi = class {
  constructor(clientId, apiKey) {
    this.wikiBaseUrl = "https://ima.qq.com/openapi/wiki/v1";
    this.noteBaseUrl = "https://ima.qq.com/openapi/note/v1";
    this.clientId = clientId;
    this.apiKey = apiKey;
  }
  request(_0, _1) {
    return __async(this, arguments, function* (baseUrl, endpoint, data = {}) {
      const url = `${baseUrl}/${endpoint}`;
      const resp = yield (0, import_obsidian.requestUrl)({
        url,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "ima-openapi-clientid": this.clientId,
          "ima-openapi-apikey": this.apiKey
        },
        body: JSON.stringify(data)
      });
      if (resp.json.code !== 0) {
        throw new Error(`${endpoint}: ${resp.json.msg || "\u672A\u77E5\u9519\u8BEF"}`);
      }
      return resp.json.data;
    });
  }
  searchAllKnowledgeBases() {
    return __async(this, null, function* () {
      const allKbs = [];
      let cursor = "";
      while (true) {
        const data = yield this.request(this.wikiBaseUrl, "search_knowledge_base", {
          query: "",
          cursor,
          limit: 20
        });
        const kbs = (data == null ? void 0 : data.info_list) || [];
        if (kbs.length === 0)
          break;
        allKbs.push(...kbs);
        if (data.is_end)
          break;
        cursor = data.next_cursor || "";
        if (!cursor)
          break;
      }
      return allKbs;
    });
  }
  getAllKnowledgeList(kbId) {
    return __async(this, null, function* () {
      const allItems = [];
      let cursor = "";
      while (true) {
        const data = yield this.request(this.wikiBaseUrl, "get_knowledge_list", {
          knowledge_base_id: kbId,
          cursor,
          limit: 50
        });
        const items = (data == null ? void 0 : data.knowledge_list) || [];
        if (items.length === 0)
          break;
        allItems.push(...items);
        if (data.is_end)
          break;
        cursor = data.next_cursor || "";
        if (!cursor)
          break;
      }
      return allItems;
    });
  }
  exportMedia(mediaId) {
    return __async(this, null, function* () {
      var _a;
      try {
        const data = yield this.request(this.wikiBaseUrl, "export_media_for_ima_sandbox", {
          media_id: mediaId
        });
        const downloadUrl = (_a = data == null ? void 0 : data.media_content_url_info) == null ? void 0 : _a.url;
        if (!downloadUrl)
          return null;
        const resp = yield (0, import_obsidian.requestUrl)({ url: downloadUrl, method: "GET" });
        return resp.text;
      } catch (e) {
        return null;
      }
    });
  }
  getDocContent(docId) {
    return __async(this, null, function* () {
      try {
        const data = yield this.request(this.noteBaseUrl, "get_doc_content", {
          doc_id: docId,
          target_content_format: 1
        });
        if (data == null ? void 0 : data.content)
          return data.content;
        return null;
      } catch (e) {
        return null;
      }
    });
  }
  getDocContentWithError(docId) {
    return __async(this, null, function* () {
      try {
        const data = yield this.request(this.noteBaseUrl, "get_doc_content", {
          doc_id: docId,
          target_content_format: 1
        });
        if (data == null ? void 0 : data.content) {
          return { success: true, content: data.content };
        }
        return { success: false, error: "\u5185\u5BB9\u4E3A\u7A7A" };
      } catch (e) {
        return { success: false, error: e.message };
      }
    });
  }
  exportMediaWithError(mediaId) {
    return __async(this, null, function* () {
      var _a;
      try {
        const data = yield this.request(this.wikiBaseUrl, "export_media_for_ima_sandbox", {
          media_id: mediaId
        });
        const downloadUrl = (_a = data == null ? void 0 : data.media_content_url_info) == null ? void 0 : _a.url;
        if (!downloadUrl) {
          return { success: false, error: "\u65E0\u4E0B\u8F7D\u94FE\u63A5" };
        }
        const resp = yield (0, import_obsidian.requestUrl)({ url: downloadUrl, method: "GET" });
        return { success: true, content: resp.text };
      } catch (e) {
        return { success: false, error: e.message };
      }
    });
  }
  listNotebooks() {
    return __async(this, null, function* () {
      const notebooks = [];
      let cursor = "0";
      while (true) {
        try {
          const data = yield this.request(this.noteBaseUrl, "list_note_by_folder_id", {
            cursor,
            limit: 20
          });
          const items = (data == null ? void 0 : data.notes) || [];
          if (items.length === 0)
            break;
          notebooks.push(...items);
          if (data.is_end)
            break;
          cursor = data.next_cursor || "";
          if (!cursor || cursor === "0")
            break;
        } catch (e) {
          break;
        }
      }
      return notebooks;
    });
  }
};
var ImaSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "IMA \u540C\u6B65\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("Client ID").setDesc("\u5DF2\u81EA\u52A8\u914D\u7F6E").addText((text) => text.setValue(this.plugin.settings.clientId));
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("\u4ECE https://ima.qq.com/agent-interface \u83B7\u53D6").addText((text) => {
      text.inputEl.type = "password";
      text.setValue(this.plugin.settings.apiKey);
      text.onChange((value) => __async(this, null, function* () {
        this.plugin.settings.apiKey = value;
        yield this.plugin.saveSettings();
      }));
    });
    new import_obsidian.Setting(containerEl).setName("\u76EE\u6807\u6587\u4EF6\u5939").setDesc(`\u5F53\u524D: ${this.plugin.settings.targetFolder}`).addButton((btn) => btn.setButtonText("\u9009\u62E9\u6587\u4EF6\u5939").onClick(() => {
      new FolderSelectModal(this.app, this.plugin, this).open();
    }));
    new import_obsidian.Setting(containerEl).setName("\u540C\u6B65\u7B14\u8BB0\u672C").setDesc("\u540C\u6B65\u4F60\u81EA\u5DF1\u7684\u7B14\u8BB0\u672C\u7B14\u8BB0").addButton((btn) => btn.setButtonText("\u540C\u6B65\u7B14\u8BB0\u672C").onClick(() => {
      this.plugin.syncNotebookNotes();
    }));
    new import_obsidian.Setting(containerEl).setName("\u540C\u6B65\u5206\u4EAB\u94FE\u63A5").setDesc("\u8F93\u5165\u5206\u4EAB\u94FE\u63A5\uFF0C\u5355\u4E2A\u540C\u6B65").addButton((btn) => btn.setButtonText("\u8F93\u5165\u94FE\u63A5").onClick(() => {
      this.plugin.syncFromShareLink();
    }));
    new import_obsidian.Setting(containerEl).setName("\u540C\u6B65\u77E5\u8BC6\u5E93").setDesc("\u540C\u6B65\u77E5\u8BC6\u5E93\u91CC\u7684\u7B14\u8BB0\uFF08\u53EF\u80FD\u6743\u9650\u4E0D\u8DB3\uFF09").addButton((btn) => btn.setButtonText("\u9009\u62E9\u77E5\u8BC6\u5E93").onClick(() => {
      new KnowledgeBaseModal(this.app, this.plugin).open();
    }));
    if (this.plugin.settings.selectedKbs.length > 0) {
      containerEl.createEl("p", {
        text: `\u5DF2\u9009\u62E9 ${this.plugin.settings.selectedKbs.length} \u4E2A\u77E5\u8BC6\u5E93`,
        cls: "setting-item-description"
      });
    }
    new import_obsidian.Setting(containerEl).setName("\u5168\u91CF\u540C\u6B65\u77E5\u8BC6\u5E93").setDesc("\u540C\u6B65\u6240\u6709\u5DF2\u9009\u77E5\u8BC6\u5E93").addButton((btn) => btn.setButtonText("\u5168\u91CF\u540C\u6B65").setCta().onClick(() => {
      this.plugin.syncAll(true);
    }));
  }
};
var FolderSelectModal = class extends import_obsidian.Modal {
  constructor(app, plugin, settingTab) {
    super(app);
    this.plugin = plugin;
    this.settingTab = settingTab;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u9009\u62E9\u6587\u4EF6\u5939" });
    const folders = this.getAvailableFolders();
    const selectEl = contentEl.createEl("select");
    folders.forEach((folder) => {
      const option = selectEl.createEl("option");
      option.value = folder;
      option.textContent = folder || "\u6839\u76EE\u5F55";
      if (folder === this.plugin.settings.targetFolder) {
        option.selected = true;
      }
    });
    const btnContainer = contentEl.createDiv();
    const cancelBtn = btnContainer.createEl("button", { text: "\u53D6\u6D88" });
    cancelBtn.onclick = () => this.close();
    const saveBtn = btnContainer.createEl("button", { text: "\u786E\u5B9A", cls: "mod-cta" });
    saveBtn.onclick = () => __async(this, null, function* () {
      this.plugin.settings.targetFolder = selectEl.value;
      yield this.plugin.saveSettings();
      this.close();
      new import_obsidian.Notice("\u6587\u4EF6\u5939\u5DF2\u66F4\u65B0");
      this.settingTab.display();
    });
  }
  getAvailableFolders() {
    const folders = new Set(["", "IMA\u77E5\u8BC6\u5E93"]);
    this.app.vault.getFiles().forEach((file) => {
      const parts = file.path.split("/").slice(0, -1);
      let current = "";
      parts.forEach((part) => {
        current += (current ? "/" : "") + part;
        folders.add(current);
      });
    });
    return Array.from(folders).sort();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ShareNoteModal = class extends import_obsidian.Modal {
  constructor(app, plugin, initialUrl = null) {
    super(app);
    this.plugin = plugin;
    this.initialUrl = initialUrl;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u540C\u6B65\u5206\u4EAB\u94FE\u63A5\u7B14\u8BB0" });
    contentEl.createEl("p", { text: "\u7C98\u8D34 IMA \u5206\u4EAB\u94FE\u63A5\u6216\u7B14\u8BB0ID\uFF1A" });
    const inputEl = contentEl.createEl("input", {
      type: "text",
      placeholder: "https://ima.qq.com/note/share/_AweNbOP8AufLZwbbFNmOw"
    });
    inputEl.style.width = "100%";
    inputEl.style.marginBottom = "10px";
    if (this.initialUrl) {
      inputEl.value = this.initialUrl;
    }
    const btnContainer = contentEl.createDiv();
    const syncBtn = btnContainer.createEl("button", { text: "\u540C\u6B65", cls: "mod-cta" });
    syncBtn.onclick = () => __async(this, null, function* () {
      const input = inputEl.value.trim();
      if (!input) {
        new import_obsidian.Notice("\u8BF7\u8F93\u5165\u5206\u4EAB\u94FE\u63A5\u6216\u7B14\u8BB0ID");
        return;
      }
      let noteId = input;
      const match = input.match(/note\/share\/([^?]+)/);
      if (match) {
        noteId = match[1];
      }
      new import_obsidian.Notice("\u6B63\u5728\u83B7\u53D6\u7B14\u8BB0...");
      this.close();
      try {
        const api = new ImaApi(this.plugin.settings.clientId, this.plugin.settings.apiKey);
        const content = yield api.getDocContent(noteId);
        if (content) {
          const filePath = `${this.plugin.settings.targetFolder}/\u5206\u4EAB\u7B14\u8BB0/${noteId}.md`;
          const frontMatter = `---
source: IMA\u5206\u4EAB
note_id: "${noteId}"
sync_time: "${new Date().toISOString()}"
---

`;
          yield this.plugin.saveFile(filePath, frontMatter + content);
          new import_obsidian.Notice("\u7B14\u8BB0\u540C\u6B65\u6210\u529F\uFF01");
        } else {
          new import_obsidian.Notice("\u65E0\u6CD5\u83B7\u53D6\u7B14\u8BB0\u5185\u5BB9\uFF0C\u53EF\u80FD\u6743\u9650\u4E0D\u8DB3");
        }
      } catch (e) {
        new import_obsidian.Notice("\u540C\u6B65\u5931\u8D25: " + e.message);
      }
    });
    const cancelBtn = btnContainer.createEl("button", { text: "\u53D6\u6D88" });
    cancelBtn.onclick = () => this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var NotebookNotesModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    return __async(this, null, function* () {
      const { contentEl } = this;
      contentEl.createEl("h2", { text: "\u52A0\u8F7D\u7B14\u8BB0\u672C..." });
      try {
        const api = new ImaApi(this.plugin.settings.clientId, this.plugin.settings.apiKey);
        this.notebooks = yield api.listNotebooks();
        this.displayNotebooks();
      } catch (e) {
        contentEl.empty();
        contentEl.createEl("h2", { text: "\u52A0\u8F7D\u5931\u8D25" });
        contentEl.createEl("p", { text: "\u65E0\u6CD5\u83B7\u53D6\u7B14\u8BB0\u672C\u5217\u8868" });
      }
    });
  }
  displayNotebooks() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u7B14\u8BB0\u672C\u7B14\u8BB0" });
    contentEl.createEl("p", { text: "\u8FD9\u662F\u4F60\u81EA\u5DF1\u7684\u7B14\u8BB0\u672C\u7B14\u8BB0\uFF0C\u53EF\u4EE5\u6B63\u5E38\u540C\u6B65" });
    if (!this.notebooks || this.notebooks.length === 0) {
      contentEl.createEl("p", { text: "\u672A\u627E\u5230\u7B14\u8BB0\u672C\u7B14\u8BB0" });
      return;
    }
    const selectedNotes = new Set();
    for (const note of this.notebooks) {
      const noteDiv = contentEl.createDiv();
      noteDiv.style.marginBottom = "8px";
      const checkbox = noteDiv.createEl("input", { type: "checkbox" });
      checkbox.style.marginRight = "8px";
      noteDiv.createEl("span", { text: note.title || "\u672A\u547D\u540D" });
      checkbox.onchange = () => {
        if (checkbox.checked) {
          selectedNotes.add(note.doc_id);
        } else {
          selectedNotes.delete(note.doc_id);
        }
      };
    }
    const btnContainer = contentEl.createDiv();
    btnContainer.style.marginTop = "20px";
    const selectAllBtn = btnContainer.createEl("button", { text: "\u5168\u9009" });
    selectAllBtn.onclick = () => {
      this.notebooks.forEach((n) => selectedNotes.add(n.doc_id));
      this.displayNotebooks();
    };
    const cancelBtn = btnContainer.createEl("button", { text: "\u53D6\u6D88" });
    cancelBtn.onclick = () => this.close();
    const syncBtn = btnContainer.createEl("button", { text: "\u540C\u6B65\u9009\u4E2D", cls: "mod-cta" });
    syncBtn.onclick = () => __async(this, null, function* () {
      if (selectedNotes.size === 0) {
        new import_obsidian.Notice("\u8BF7\u9009\u62E9\u8981\u540C\u6B65\u7684\u7B14\u8BB0");
        return;
      }
      this.close();
      yield this.syncSelectedNotes(Array.from(selectedNotes));
    });
  }
  syncSelectedNotes(noteIds) {
    return __async(this, null, function* () {
      new import_obsidian.Notice(`\u5F00\u59CB\u540C\u6B65 ${noteIds.length} \u4E2A\u7B14\u8BB0...`);
      const api = new ImaApi(this.plugin.settings.clientId, this.plugin.settings.apiKey);
      let syncedCount = 0;
      for (const noteId of noteIds) {
        try {
          const content = yield api.getDocContent(noteId);
          if (content) {
            const filePath = `${this.plugin.settings.targetFolder}/\u6211\u7684\u7B14\u8BB0\u672C/${noteId}.md`;
            const frontMatter = `---
source: IMA\u7B14\u8BB0\u672C
doc_id: "${noteId}"
sync_time: "${new Date().toISOString()}"
---

`;
            yield this.plugin.saveFile(filePath, frontMatter + content);
            syncedCount++;
          }
        } catch (e) {
          console.warn(`\u8DF3\u8FC7: ${noteId}`, e);
        }
      }
      new import_obsidian.Notice(`\u7B14\u8BB0\u672C\u7B14\u8BB0\u540C\u6B65\u5B8C\u6210\uFF01\u540C\u6B65 ${syncedCount} \u4E2A`);
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var KnowledgeBaseModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    return __async(this, null, function* () {
      this.contentEl.createEl("h2", { text: "\u52A0\u8F7D\u4E2D..." });
      try {
        const api = new ImaApi(this.plugin.settings.clientId, this.plugin.settings.apiKey);
        this.knowledgeBases = yield api.searchAllKnowledgeBases();
        this.displayKbs();
      } catch (e) {
        this.contentEl.empty();
        this.contentEl.createEl("h2", { text: "\u52A0\u8F7D\u5931\u8D25" });
        this.contentEl.createEl("p", { text: "\u8BF7\u68C0\u67E5 API Key \u662F\u5426\u6B63\u786E" });
      }
    });
  }
  displayKbs() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u9009\u62E9\u8981\u540C\u6B65\u7684\u77E5\u8BC6\u5E93" });
    contentEl.createEl("p", { text: "\u26A0\uFE0F \u6CE8\u610F\uFF1A\u77E5\u8BC6\u5E93\u91CC\u7684\u7B14\u8BB0\u53EF\u80FD\u9700\u8981\u6743\u9650\u624D\u80FD\u8BFB\u53D6" });
    if (!this.knowledgeBases || this.knowledgeBases.length === 0) {
      contentEl.createEl("p", { text: "\u672A\u627E\u5230\u53EF\u7528\u77E5\u8BC6\u5E93" });
      return;
    }
    const selectedKbs = new Set(this.plugin.settings.selectedKbs);
    for (const kb of this.knowledgeBases) {
      const kbDiv = contentEl.createDiv();
      kbDiv.style.marginBottom = "8px";
      kbDiv.style.padding = "8px";
      kbDiv.style.borderBottom = "1px solid #eee";
      const checkbox = kbDiv.createEl("input", { type: "checkbox" });
      checkbox.checked = selectedKbs.has(kb.kb_id);
      checkbox.style.marginRight = "8px";
      const label = kbDiv.createEl("span", { text: ` ${kb.kb_name} ` });
      label.style.fontWeight = "bold";
      const roleLabel = kbDiv.createEl("span", {
        text: ` [${kb.role_type}]`,
        cls: "setting-item-description"
      });
      if (kb.kb_desc) {
        kbDiv.createEl("p", { text: kb.kb_desc, cls: "setting-item-description" });
      }
      checkbox.onchange = () => {
        if (checkbox.checked) {
          selectedKbs.add(kb.kb_id);
        } else {
          selectedKbs.delete(kb.kb_id);
        }
      };
    }
    const btnContainer = contentEl.createDiv();
    btnContainer.style.marginTop = "20px";
    const selectAllBtn = btnContainer.createEl("button", { text: "\u5168\u9009" });
    selectAllBtn.onclick = () => {
      this.knowledgeBases.forEach((kb) => selectedKbs.add(kb.kb_id));
      this.displayKbs();
    };
    const cancelBtn = btnContainer.createEl("button", { text: "\u53D6\u6D88" });
    cancelBtn.onclick = () => this.close();
    const syncBtn = btnContainer.createEl("button", { text: "\u5F00\u59CB\u540C\u6B65", cls: "mod-cta" });
    syncBtn.onclick = () => __async(this, null, function* () {
      const selected = Array.from(selectedKbs);
      if (selected.length === 0) {
        new import_obsidian.Notice("\u8BF7\u81F3\u5C11\u9009\u62E9\u4E00\u4E2A\u77E5\u8BC6\u5E93");
        return;
      }
      this.plugin.settings.selectedKbs = selected;
      this.plugin.settings.selectedNotes = {};
      yield this.plugin.saveSettings();
      this.close();
      this.plugin.syncAll(true, selected);
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var main_default = ImaPlugin;
